from pathlib import Path

p = Path('themes/argent.html')
text = p.read_text(encoding='utf-8')

start = text.index('<div class="pillar-grid" id="construction">')
end = text.index('<div class="foundation">', start)

new_grid = '''<div class="pillar-grid" id="construction">
<article class="pillar" id="budget"><div class="kicker">01</div><h2>Budget & premiers euros</h2><p>Comprendre ce qui entre, ce qui sort et créer une première marge avant de parler placement.</p><div class="pillar-links"><a href="../dossiers/premier-salaire-18-ans-chez-parents.html"><strong>Premier salaire : j’ai peu de charges, que faire de l’argent ? →</strong></a><a href="../dossiers/audit-budget-60-minutes.html">Faire l’audit de mon budget →</a><a href="../dossiers/depenses-recurrentes-abonnements-assurances.html">Réduire abonnements, assurances et dépenses récurrentes →</a><a href="../dossiers/prix-attendre-finances.html">Comprendre ce que me coûte le fait d’attendre →</a><a href="../dossiers/cout-reel-voiture-achat-credit-loa-lld.html">Calculer le coût réel d’une voiture →</a></div></article>
<article class="pillar" id="epargne"><div class="kicker">02</div><h2>Épargne & sécurité</h2><p>Passer du premier euro mis de côté à une réserve réellement utile, puis identifier la part qui peut rester investie longtemps.</p><div class="pillar-links"><a href="../articles/construire-epargne-de-zero.html"><strong>Je pars de zéro : construire ma première épargne →</strong></a><a href="../dossiers/liquidites-reserve-securite.html">Combien garder disponible et où ? →</a><a href="../dossiers/seuils-maturite-patrimoniale.html">Savoir quand ma réserve devient du capital investissable →</a><a href="../articles/grosse-entree-argent-que-faire.html">Je viens de recevoir une grosse somme : quoi faire d’abord ? →</a><a href="../dossiers/patrimoine-marge-de-manoeuvre.html">Mesurer ma marge de manœuvre financière →</a></div></article>
<article class="pillar" id="enveloppes"><div class="kicker">03</div><h2>Comptes & enveloppes</h2><p>Livret A, LDDS, LEP, PEA, assurance-vie, PEE, PER ou CTO : comprendre la fonction de chaque contenant avant de multiplier les produits.</p><div class="pillar-links"><a href="../dossiers/finances-enveloppes-fiscalite.html"><strong>Quels comptes et enveloppes dois-je avoir ? →</strong></a><a href="../dossiers/premier-salaire-18-ans-chez-parents.html">À 18–25 ans : quoi ouvrir et dans quel ordre ? →</a><a href="../dossiers/patrimoine-selon-age-construire-utiliser.html">Voir comment les enveloppes évoluent selon la situation →</a><a href="../articles/checklist-avant-placement-conseiller.html">Vérifier un placement ou un conseiller avant de signer →</a></div></article>
<article class="pillar" id="investissement"><div class="kicker">04</div><h2>Investissement</h2><p>Une fois la sécurité et les enveloppes comprises : choisir les actifs, construire l’allocation, diversifier et gérer le risque.</p><div class="pillar-links"><a href="../dossiers/premier-investissement-comment-commencer.html"><strong>Commencer : investir ses premiers 100, 500 ou 1 000 € →</strong></a><a href="../dossiers/allocation-patrimoine-selon-situation.html">J’investis déjà : 8 allocations selon la situation →</a><a href="../dossiers/classes-actifs-allocation-patrimoine.html">Comprendre les grandes classes d’actifs →</a><a href="../dossiers/finances-allocation-portefeuille.html">Construire une allocation patrimoniale →</a><a href="../articles/choisir-etf-mondial-debutant.html">Choisir un ETF diversifié →</a><a href="../articles/frais-fiscalite-rendement-net.html">Mesurer frais, fiscalité et rendement net →</a><a href="../dossiers/rembourser-credit-ou-investir.html">Rembourser un crédit ou investir ? →</a><a href="../outil-microscope-pea.html">Analyser concentration et chevauchements dans mon PEA →</a><a href="../parcours-argent.html">Entrer dans Investissement →</a></div></article>
<article class="pillar" id="immobilier"><div class="kicker">05</div><h2>Immobilier</h2><p>L’immobilier est une grande décision d’allocation et de vie, pas l’étape obligatoire qui suit les premiers euros épargnés.</p><div class="immobilier-map"><div><strong>Habiter</strong><span>Résidence principale, coût complet, copropriété, mobilité.</span></div><div><strong>Exploiter</strong><span>Nue, meublée, courte durée, rendement net et gestion.</span></div><div><strong>Diversifier</strong><span>Garages, parkings, locaux commerciaux et immobilier indirect.</span></div><div><strong>Transformer</strong><span>Louer une partie, diviser, changer d’usage, vendre ou conserver.</span></div></div><div class="pillar-links"><a href="../dossiers/immobilier-allocation-globale-patrimoine.html">Quelle place donner à l’immobilier dans le patrimoine ? →</a><a href="../dossiers/cout-complet-achat-immobilier.html">Calculer le coût complet d’un achat →</a><a href="../dossiers/audit-copropriete-avant-achat.html">Auditer une copropriété avant de signer →</a><a href="../dossiers/finances-residence-principale.html">Acheter ou louer sa résidence principale →</a><a href="../dossiers/finances-investissement-locatif.html">Tester rendement, cash-flow et risques locatifs →</a><a href="../dossiers/bien-immobilier-garder-vendre-transformer.html">Garder, vendre, louer ou transformer un bien ? →</a></div><div class="pillar-tools"><strong>Outils immobiliers</strong><div class="pillar-links"><a href="../simulateur-capacite-emprunt.html">Tester sa capacité d’emprunt →</a><a href="../simulateur-acheter-ou-louer.html">Comparer acheter ou louer →</a><a href="../simulateur-investissement-locatif.html">Tester un investissement locatif →</a><a href="../simulateur-vendre-ou-conserver.html">Vendre ou conserver un bien →</a></div></div></article>
<article class="pillar" id="long-terme"><div class="kicker">06</div><h2>Retraite & transmission</h2><p>Transformer le patrimoine en revenus, préserver la marge de sécurité et préparer le passage à la génération suivante.</p><div class="pillar-links"><a href="../dossiers/preparer-retraite-droits-epargne-logement.html">Préparer sa retraite 5, 10, 20 ou 30 ans avant →</a><a href="../dossiers/finances-retraite-decumulation.html">Transformer progressivement le patrimoine en revenus →</a><a href="../dossiers/finances-transmission-patrimoine.html">Préparer une transmission →</a><a href="../dossiers/finances-cadre-global.html">Revoir l’ensemble du patrimoine →</a></div></article>
</div>'''

text = text[:start] + new_grid + text[end:]

old_top = '<a class="maturity-card basics" href="#budget"><span class="step">01 · Je pose les bases</span><h3>Reprendre mes finances et créer de la marge.</h3><p>Pour commencer sans avoir besoin de connaître le vocabulaire de l’investissement.</p><ul><li>budget et dépenses</li><li>dettes et réserve de sécurité</li><li>première épargne</li><li>premiers investissements</li></ul><span class="go">Commencer par les bases →</span></a>'
new_top = '<a class="maturity-card basics" href="#budget"><span class="step">01 · Je pose les bases</span><h3>Budget, premiers euros, épargne puis sécurité.</h3><p>Pour commencer sans devoir fouiller parmi l’immobilier ou les placements.</p><ul><li>premier salaire et budget</li><li>première épargne</li><li>réserve disponible</li><li>capital réellement investissable</li></ul><span class="go">Commencer par les bases →</span></a>'
assert old_top in text
text = text.replace(old_top, new_top, 1)

old_build = '<a class="maturity-card build" href="#construction"><span class="step">02 · Je fais grandir mon patrimoine</span><h3>Faire travailler mon épargne sans me disperser.</h3><p>Pour comparer immobilier, placements, crédit et diversification.</p><ul><li>acheter ou louer</li><li>investir et diversifier</li><li>choisir ses enveloppes</li><li>préparer le long terme</li></ul><span class="go">Construire mon patrimoine →</span></a>'
new_build = '<a class="maturity-card build" href="#epargne"><span class="step">02 · J’organise ce que j’ai déjà</span><h3>Épargne, enveloppes, puis investissements.</h3><p>Pour donner une fonction à l’argent avant de choisir un bien ou un placement.</p><ul><li>séparer sécurité et projets</li><li>choisir les bonnes enveloppes</li><li>investir seulement le long terme</li><li>intégrer ensuite l’immobilier</li></ul><span class="go">Organiser mon argent →</span></a>'
assert old_build in text
text = text.replace(old_build, new_build, 1)

p.write_text(text, encoding='utf-8')

report = Path('reports/content-review-decisions-2026-08-16-batch-34.md')
report.write_text('''# Lot 34 — cohérence du parcours Patrimoine\n\n## Problème\nLe hub rendait l’épargne élémentaire moins visible que l’immobilier et mélangeait la question des enveloppes avec l’investissement. Un débutant pouvait croire que le parcours naturel était budget → immobilier → investissement.\n\n## Correction non destructive\nAucun dossier ni URL supprimé. Le hub est réordonné en six étapes visibles :\n1. Budget & premiers euros\n2. Épargne & sécurité\n3. Comptes & enveloppes\n4. Investissement\n5. Immobilier\n6. Retraite & transmission\n\n## Doctrine\nLa progression visible doit distinguer : créer une marge → constituer une épargne → choisir les contenants → investir → décider de la place de l’immobilier → organiser l’usage long terme. L’âge et le niveau de patrimoine ne déterminent pas automatiquement le point d’entrée.\n''', encoding='utf-8')
