from pathlib import Path

# --- Patrimoine hub: four visible layers, all existing deep content preserved ---
p = Path('themes/argent.html')
t = p.read_text(encoding='utf-8')

t = t.replace('.patrimoine-hub .maturity-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.8rem}', '.patrimoine-hub .maturity-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.8rem}', 1)

head_old = '<div class="maturity-head"><div class="kicker">Où en êtes-vous ?</div><h2 id="maturity-title">Commencez par ce que vous devez faire maintenant.</h2><p>Ces trois chemins ne sont ni des niveaux de richesse ni des cases définitives. Ils servent seulement à montrer d’abord les décisions les plus utiles aujourd’hui.</p></div>'
head_new = '<div class="maturity-head"><div class="kicker">Construire couche après couche</div><h2 id="maturity-title">Posez les bases, apprenez, renforcez, puis pilotez.</h2><p>Le patrimoine ne se construit pas par produits. On sécurise d’abord le socle, on apprend à investir sans le fragiliser, puis on ajoute progressivement les couches utiles.</p></div>'
assert head_old in t
t = t.replace(head_old, head_new, 1)

mstart = t.index('<div class="maturity-grid">')
mend = t.index('</div><div class="maturity-note">', mstart) + len('</div>')
new_maturity = '''<div class="maturity-grid"><a class="maturity-card basics" href="#bases"><span class="step">01 · Poser les bases</span><h3>Créer de la marge et commencer à épargner.</h3><p>Budget, premiers euros, réserve et projets proches : le socle doit tenir avant toute prise de risque.</p><ul><li>comprendre mes flux</li><li>mettre de côté régulièrement</li><li>constituer une réserve utile</li><li>identifier le capital vraiment disponible</li></ul><span class="go">Poser les bases →</span></a><a class="maturity-card build" href="#apprendre"><span class="step">02 · Apprendre à investir</span><h3>Comprendre avant d’augmenter les montants.</h3><p>Risque, rendement, actifs, ETF et enveloppes : commencer petit permet d’apprendre sans mettre le socle en danger.</p><ul><li>comprendre ce que j’achète</li><li>choisir une enveloppe adaptée</li><li>faire un premier investissement</li><li>apprendre à traverser une baisse</li></ul><span class="go">Apprendre à investir →</span></a><a class="maturity-card build" href="#renforcer"><span class="step">03 · Renforcer</span><h3>Augmenter, diversifier et organiser l’ensemble.</h3><p>Quand les bases et les mécanismes sont compris, les versements, les enveloppes et les actifs peuvent être renforcés sans empiler au hasard.</p><ul><li>augmenter les flux investis</li><li>diversifier actifs et enveloppes</li><li>intégrer l’immobilier si pertinent</li><li>contrôler concentrations et dettes</li></ul><span class="go">Renforcer mon patrimoine →</span></a><a class="maturity-card pilot" href="#piloter"><span class="step">04 · Piloter & utiliser</span><h3>Faire servir le patrimoine à la vie.</h3><p>Quand plusieurs couches existent, l’enjeu devient l’arbitrage global : options de vie, revenus, retraite, protection et transmission.</p><ul><li>piloter l’allocation globale</li><li>acheter du temps et de la liberté</li><li>préparer les retraits</li><li>protéger et transmettre</li></ul><span class="go">Piloter et utiliser →</span></a></div>'''
t = t[:mstart] + new_maturity + t[mend:]

t = t.replace('<div class="maturity-note">Vous pouvez passer d’un chemin à l’autre à tout moment. Le site ne déduit aucun « niveau » à partir de vos données.</div>', '<div class="maturity-note">Ces couches décrivent une logique de construction, pas un classement des personnes. Un héritage peut donner beaucoup de capital sans expérience ; un jeune peut au contraire disposer déjà d’un socle préparé.</div>', 1)

# Remove the large threshold callout here; the threshold link is kept inside layer 1.
fstart = t.index('<div class="foundation" style="margin-top:1rem">')
fend = t.index('<div class="pillar-grid" id="construction">', fstart)
t = t[:fstart] + t[fend:]

pstart = t.index('<div class="pillar-grid" id="construction">')
pend = t.index('<div class="foundation">', pstart)
new_layers = '''<div class="pillar-grid" id="construction">
<article class="pillar" id="bases"><div class="kicker">Couche 01</div><h2>Poser les bases</h2><p>Le premier objectif n’est pas d’investir : c’est de créer une marge durable, une épargne disponible et une réserve adaptée à la vie qui arrive.</p><div class="pillar-links"><a href="../dossiers/premier-salaire-18-ans-chez-parents.html"><strong>Premier salaire : que faire de l’argent ? →</strong></a><a href="../articles/construire-epargne-de-zero.html"><strong>Je pars de zéro : construire ma première épargne →</strong></a><a href="../dossiers/audit-budget-60-minutes.html">Faire l’audit de mon budget →</a><a href="../dossiers/liquidites-reserve-securite.html">Combien garder disponible et où ? →</a><a href="../dossiers/seuils-maturite-patrimoniale.html">Quand mon épargne devient-elle réellement investissable ? →</a><a href="../articles/grosse-entree-argent-que-faire.html">Je reçois une grosse somme : quoi faire d’abord ? →</a></div><div class="pillar-tools"><strong>Protéger le socle</strong><div class="pillar-links"><a href="../dossiers/depenses-recurrentes-abonnements-assurances.html">Réduire les dépenses récurrentes →</a><a href="../dossiers/assurer-ou-autoassurer-risques.html">Quels risques assurer ou autoassurer ? →</a><a href="../dossiers/cout-reel-voiture-achat-credit-loa-lld.html">Mesurer le coût réel d’une voiture →</a><a href="../simulateur-prix-attendre.html">Calculer ce que me coûte le fait d’attendre →</a></div></div></article>
<article class="pillar" id="apprendre"><div class="kicker">Couche 02</div><h2>Apprendre à investir</h2><p>Une fois le socle protégé, on apprend les mécanismes avec une part de capital réellement long terme avant de chercher à optimiser.</p><div class="pillar-links"><a href="../dossiers/premier-investissement-comment-commencer.html"><strong>Faire son premier investissement sans brûler les étapes →</strong></a><a href="../dossiers/classes-actifs-allocation-patrimoine.html">Comprendre les grandes classes d’actifs →</a><a href="../articles/choisir-etf-mondial-debutant.html">Comprendre et choisir un ETF diversifié →</a><a href="../dossiers/finances-enveloppes-fiscalite.html">Comprendre PEA, assurance-vie, CTO et PER →</a><a href="../articles/frais-fiscalite-rendement-net.html">Comprendre frais, fiscalité et rendement net →</a><a href="../articles/checklist-avant-placement-conseiller.html">Vérifier un placement ou un conseiller avant de signer →</a><a href="../parcours-argent.html">Entrer dans le parcours Investir son capital →</a></div></article>
<article class="pillar" id="renforcer"><div class="kicker">Couche 03</div><h2>Renforcer & diversifier</h2><p>Les bases tiennent et l’investissement est compris : on peut augmenter les montants, répartir les risques et ajouter de nouvelles briques seulement lorsqu’elles ont une fonction.</p><div class="pillar-links"><a href="../dossiers/allocation-patrimoine-selon-situation.html"><strong>Comparer des allocations selon ma situation →</strong></a><a href="../dossiers/finances-allocation-portefeuille.html">Construire une allocation patrimoniale →</a><a href="../outil-microscope-pea.html">Repérer concentrations et chevauchements dans mon PEA →</a><a href="../dossiers/rembourser-credit-ou-investir.html">Rembourser une dette ou renforcer les investissements ? →</a><a href="../articles/investir-grosse-somme-dun-coup-ou-progressivement.html">Investir une grosse somme d’un coup ou progressivement ? →</a></div><div class="pillar-tools"><strong>Ajouter la brique immobilière si elle a du sens</strong><div class="pillar-links"><a href="../dossiers/immobilier-allocation-globale-patrimoine.html">Quelle place donner à l’immobilier dans le patrimoine ? →</a><a href="../dossiers/finances-residence-principale.html">Acheter ou louer sa résidence principale ? →</a><a href="../dossiers/finances-investissement-locatif.html">Tester un investissement locatif →</a><a href="../dossiers/cout-complet-achat-immobilier.html">Calculer le coût complet d’un achat →</a><a href="../dossiers/audit-copropriete-avant-achat.html">Auditer une copropriété avant de signer →</a><a href="../dossiers/location-nue-ou-meublee-comparer.html">Comparer location nue et meublée →</a><a href="../dossiers/location-courte-duree-meuble-tourisme.html">Comprendre la courte durée →</a><a href="../dossiers/garages-parkings-locaux-commerciaux.html">Garages, parkings et locaux commerciaux →</a></div></div><div class="pillar-tools"><strong>Outils immobiliers</strong><div class="pillar-links"><a href="../simulateur-capacite-emprunt.html">Tester sa capacité d’emprunt →</a><a href="../simulateur-acheter-ou-louer.html">Comparer acheter ou louer →</a><a href="../simulateur-investissement-locatif.html">Tester un investissement locatif →</a><a href="../simulateur-vendre-ou-conserver.html">Vendre ou conserver un bien →</a><a href="../simulateur-comparer-strategies-immobilieres.html">Comparer trois stratégies immobilières →</a></div></div></article>
<article class="pillar" id="piloter"><div class="kicker">Couche 04</div><h2>Piloter, utiliser & transmettre</h2><p>Quand plusieurs couches sont en place, le sujet n’est plus d’ajouter des produits mais de faire travailler l’ensemble au service des objectifs de vie.</p><div class="pillar-links"><a href="../mon-espace.html"><strong>Ouvrir le cockpit patrimonial →</strong></a><a href="../dossiers/finances-cadre-global.html">Revoir l’ensemble du patrimoine →</a><a href="../dossiers/patrimoine-marge-de-manoeuvre.html">Mesurer la marge de manœuvre que le patrimoine procure →</a><a href="../dossiers/bien-immobilier-garder-vendre-transformer.html">Garder, vendre, louer ou transformer un bien ? →</a><a href="../dossiers/preparer-retraite-droits-epargne-logement.html">Préparer la retraite sans attendre la dernière ligne droite →</a><a href="../dossiers/finances-retraite-decumulation.html">Transformer progressivement le patrimoine en revenus →</a><a href="../dossiers/finances-transmission-patrimoine.html">Préparer une transmission →</a></div></article>
</div>'''
t = t[:pstart] + new_layers + t[pend:]

# Remove duplicate "Pour ceux qui pilotent déjà" callout now absorbed into layer 4.
dup = '<div class="foundation"><div><div class="kicker">Pour ceux qui pilotent déjà</div>'
if dup in t:
    dstart = t.index(dup)
    dend = t.index('<div class="start-here"', dstart)
    t = t[:dstart] + t[dend:]

p.write_text(t, encoding='utf-8')

# --- Investment sub-hub: clarify its role inside layers 2 and 3 ---
p = Path('parcours-argent.html')
t = p.read_text(encoding='utf-8')
repls = {
    '<title>Investissement — allocation, enveloppes et supports | Contre-évidence</title>': '<title>Investir son capital — apprendre, renforcer, diversifier | Contre-évidence</title>',
    '<meta name="description" content="Sous-rubrique Investissement de Contre-évidence : allocation patrimoniale, fonctions des actifs, enveloppes, ETF, frais, fiscalité et mise en œuvre."/>': '<meta name="description" content="Apprendre à investir puis renforcer son patrimoine : premiers investissements, actifs, enveloppes, allocation, diversification, frais et mise en œuvre."/>',
    '<div class="voice-signature">Investir vient après la sécurité, les projets proches et la place de l’immobilier.</div>': '<div class="voice-signature">On épargne d’abord. On apprend à investir ensuite. On renforce seulement quand les mécanismes sont compris et que le socle reste intact.</div>',
    '<h1>Investissement</h1><p>Construire l’allocation, comprendre les supports et les enveloppes, puis mesurer frais, rendement et risque avec ses propres hypothèses.</p>': '<h1>Investir son capital</h1><p>Commencer petit pour comprendre le risque, les actifs et les enveloppes ; puis augmenter, diversifier et construire une allocation quand le socle est solide.</p>',
    '.invest-hub .local-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem}': '.invest-hub .local-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}',
}
for old, new in repls.items():
    assert old in t, old
    t = t.replace(old, new, 1)

lstart = t.index('<div class="local-grid">')
lend = t.index('</div></div></section>', lstart) + len('</div>')
new_local = '''<div class="local-grid"><article class="local-card"><div class="kicker">01 · Apprendre</div><h2>Comprendre avant d’augmenter les montants</h2><p>Le premier investissement sert aussi à apprendre : ce que vous détenez, pourquoi cela peut baisser, dans quelle enveloppe le loger et comment éviter les erreurs coûteuses.</p><p><a href="dossiers/seuils-maturite-patrimoniale.html"><strong>Vérifier si mon capital est réellement investissable →</strong></a></p><p><a href="dossiers/premier-investissement-comment-commencer.html">Préparer mon premier investissement →</a></p><p><a href="dossiers/classes-actifs-allocation-patrimoine.html">Comprendre les grandes classes d’actifs →</a></p><p><a href="articles/choisir-etf-mondial-debutant.html">Comprendre un ETF diversifié →</a></p><p><a href="dossiers/finances-enveloppes-fiscalite.html">Choisir entre PEA, assurance-vie, CTO et PER →</a></p><p><a href="articles/frais-fiscalite-rendement-net.html">Mesurer frais et rendement net →</a></p></article><article class="local-card"><div class="kicker">02 · Renforcer</div><h2>Augmenter et diversifier sans empiler au hasard</h2><p>Quand les mécanismes sont compris et le plan supporte une baisse, on peut augmenter les versements, répartir les risques et contrôler l’allocation globale.</p><p><a href="dossiers/allocation-patrimoine-selon-situation.html"><strong>Comparer 8 situations concrètes →</strong></a></p><p><a href="dossiers/finances-allocation-portefeuille.html">Construire une allocation patrimoniale →</a></p><p><a href="outil-microscope-pea.html">Analyser concentrations et chevauchements →</a></p><p><a href="dossiers/rembourser-credit-ou-investir.html">Arbitrer dette et investissement →</a></p><p><a href="articles/investir-grosse-somme-dun-coup-ou-progressivement.html">Investir d’un coup ou progressivement →</a></p><p><a href="dossiers/finances-cadre-global.html">Revoir le cadre patrimonial global →</a></p></article></div>'''
t = t[:lstart] + new_local + t[lend:]

t = t.replace('<p>Budget, immobilier, investissement, retraite et transmission restent réunis dans Patrimoine.</p>', '<p>Retrouvez les quatre couches — poser les bases, apprendre à investir, renforcer, puis piloter et utiliser — dans Patrimoine.</p>', 1)

# Keep social metadata aligned.
t = t.replace('Investissement — allocation, enveloppes et supports | Contre-évidence', 'Investir son capital — apprendre, renforcer, diversifier | Contre-évidence')
t = t.replace('Sous-rubrique Investissement de Contre-évidence : allocation patrimoniale, fonctions des actifs, enveloppes, ETF, frais, fiscalité et mise en œuvre.', 'Apprendre à investir puis renforcer son patrimoine : premiers investissements, actifs, enveloppes, allocation, diversification, frais et mise en œuvre.')
p.write_text(t, encoding='utf-8')

Path('reports/content-review-decisions-2026-08-17-batch-35.md').write_text('''# Lot 35 — architecture Patrimoine en couches\n\n## Décision\nResserrer la navigation visible autour de quatre couches :\n1. Poser les bases\n2. Apprendre à investir\n3. Renforcer & diversifier\n4. Piloter, utiliser & transmettre\n\n## Principe\nOn n’accède pas à un « niveau de richesse ». On empile des fonctions sans détruire les précédentes : marge et épargne, compréhension de l’investissement, renforcement/diversification, puis pilotage et usage du patrimoine.\n\n## Effet\nLes six rubriques Budget / Épargne / Enveloppes / Investissement / Immobilier / Retraite ne sont plus six portes concurrentes. Elles sont absorbées dans les quatre couches. Les dossiers et URLs restent conservés. `parcours-argent.html` devient explicitement le sous-parcours « Investir son capital » articulé en Apprendre puis Renforcer.\n''', encoding='utf-8')
