from pathlib import Path
import re

p = Path('dossiers/inflation-comprendre-histoire-pouvoir-achat.html')
s = p.read_text(encoding='utf-8')

# Make the acquisition promise concrete without deleting the deep historical material.
s = re.sub(r'<title>.*?</title>', '<title>10 000 € aujourd’hui : combien vaudront-ils vraiment dans 5, 10 ou 20 ans ? | Contre-Évidence</title>', s, count=1)
s = re.sub(r'<meta name="description" content="[^"]*"/>', '<meta name="description" content="Inflation en euros concrets : ce que 10 000 €, un salaire, un crédit et une épargne deviennent quand les prix montent, avant d’aller plus loin dans l’histoire et les mécanismes."/>', s, count=1)
s = s.replace('<div class="kicker">Patrimoine · Comprendre</div><h1>Inflation : pourquoi votre argent perd de la valeur même quand votre compte ne baisse pas.</h1><p>Définition, causes, 80 ans d’histoire française, effets sur le pouvoir d’achat, l’épargne, le crédit et les placements. Avec les chiffres qui permettent enfin de mesurer ce que quelques pourcents changent réellement.</p><div class="dossier-hero-note"><strong>Idée centrale :</strong> l’inflation ne dit pas seulement que les prix montent. Elle dit que la quantité de biens et de services qu’un euro permet d’acheter diminue. Et sur plusieurs années, l’effet composé devient considérable.</div>', '<div class="kicker">Patrimoine · Pouvoir d’achat</div><h1>Vous avez 10 000 € sur un compte : combien vaudront-ils réellement dans 5, 10 ou 20 ans ?</h1><p>Commencez par vos euros, pas par la théorie. L’inflation change ce que votre épargne achète, la valeur réelle de votre salaire, le poids d’un crédit et le rendement qu’il faut réellement regarder.</p><div class="dossier-hero-note"><strong>Question utile :</strong> si les prix augmentent plus vite que votre argent ou vos revenus, combien de pouvoir d’achat perdez-vous réellement — et quelle décision cela change-t-il aujourd’hui ?</div>', 1)

marker = '<article class="prose">'
insert = '''<div class="answer-box"><h2>Commencez par le cas qui vous ressemble</h2><div class="decision-grid"><div class="decision-card"><h3>J’ai 10 000 € qui restent longtemps en cash</h3><p>Avec une inflation hypothétique constante de 2 %, 10 000 € ont un pouvoir d’achat équivalent à environ <strong>9 057 € dans 5 ans</strong>, <strong>8 203 € dans 10 ans</strong> et <strong>6 730 € dans 20 ans</strong>.</p></div><div class="decision-card"><h3>Mon salaire augmente moins vite que les prix</h3><p>Si les prix montent de 5 % et votre salaire de 2 %, votre revenu nominal progresse mais votre pouvoir d’achat recule. La bonne comparaison est toujours <strong>revenu après inflation</strong>.</p></div><div class="decision-card"><h3>J’ai un crédit à taux fixe</h3><p>Une mensualité fixe peut devenir relativement moins lourde si les revenus suivent l’inflation. Mais si votre salaire stagne, la hausse des autres dépenses peut au contraire tendre le budget.</p></div><div class="decision-card"><h3>Mon épargne rapporte 2 % et l’inflation est à 3 %</h3><p>Vous gagnez nominalement de l’argent mais perdez du pouvoir d’achat : le rendement réel est approximativement négatif. <strong>Le taux affiché ne suffit pas.</strong></p></div></div><p><a class="btn btn-primary" href="../simulateur-prix-attendre.html">Tester l’effet du temps et de l’inflation sur mes chiffres →</a></p></div>'''
if insert not in s:
    s = s.replace(marker, marker + insert, 1)

s = re.sub(r'<meta name="dateModified" content="[^"]*"/>', '<meta name="dateModified" content="2026-08-17"/>', s, count=1)
s = re.sub(r'article:modified_time" content="[^"]*"', 'article:modified_time" content="2026-08-17"', s, count=1)
p.write_text(s, encoding='utf-8')

Path('reports/editorial-acquisition-doctrine-2026-08-17.md').write_text('''# Doctrine acquisition — 17 août 2026\n\n## Règle\nAucun nouveau dossier d’acquisition ne doit être construit autour d’un concept abstrait.\n\nUne porte d’entrée publique doit commencer par une situation réelle, une décision ou un montant immédiatement reconnaissable.\n\n## Ordre obligatoire\n1. Situation concrète / question du visiteur.\n2. Réponse ou ordre d’action en moins d’un écran.\n3. Exemple chiffré ou comparaison.\n4. Ce qui ferait changer la réponse.\n5. Outil, checklist ou action.\n6. Seulement ensuite : mécanisme, contexte, histoire, réglementation et théorie utiles.\n\n## Interdit comme angle principal d’acquisition\n- « Comprendre X » sans situation concrète.\n- Histoire ou théorie avant l’usage.\n- Cadre global abstrait comme page d’arrivée d’un post social.\n- Lexique ou taxonomie comme promesse principale.\n\n## Autorisé\nLes pages de fond conceptuelles existantes peuvent rester comme références secondaires ou bibliothèque, mais ne doivent pas être choisies comme landing pages d’acquisition tant qu’elles n’ont pas une entrée situationnelle forte.\n\n## Test avant publication sociale\nLa page cible doit permettre en moins de 30 secondes de répondre à : « Est-ce que cette page parle exactement de mon problème et que puis-je faire maintenant ? »\n''', encoding='utf-8')
